spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/somedb
    username: someuser
    password: somepass
  jpa:
    hibernate:
      #      ddl-auto: create-drop
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect